title: Zeeshan Ahmad | Data Analyst & AI Engineer
description: Portfolio of Zeeshan Ahmad — Data Analyst, AI Engineer, and Tech Consultant based in Dallas, TX.
url: "https://zeeshan0710.github.io"
baseurl: "/portfolio"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
